export const ActionTypes = {

  LOGIN_USER: 'LOGIN_USER',
  REGISTER_GUEST: 'REGISTER_GUEST',
  REGISTER_OWNER: 'REGISTER_OWNER',

  DELETE_LISTING: 'DELETE_LISTING',
  CREATE_LISTING: 'CREATE_LISTING',
  UPDATE_LISTING: 'UPDATE_LISTING',

  ADD_BLOCKED_DATE: 'ADD_BLOCKED_DATE',
  REMOVE_BLOCKED_DATE: 'REMOVE_BLOCKED_DATE',

  FILTER_LISTING: 'FILTER_LISTING',
  FILTER_COUNT: 'FILTER_COUNT',
  GET_LISTING_BY_ID: 'GET_LISTING_BY_ID',
  GET_DRAFT_LISTING: 'GET_DRAFT_LISTING',
  GET_PENDING_LISTING: 'GET_PENDING_LISTING',
  GET_ACTIVE_LISTING: 'GET_ACTIVE_LISTING',

  GET_ALL_LISTING: 'GET_ALL_LISTING',
  GET_DECLINED_LISTING: 'GET_DECLINED_LISTING',

  GET_BOOKING_BY_ID: 'GET_BOOKING_BY_ID',
  GET_BOOKING_CHAT: 'GET_BOOKING_CHAT',
  CREATE_NEW_CHAT: 'CREATE_NEW_CHAT',
  CREATE_BOOKING: 'CREATE_BOOKING',
  GET_ACTIVE_BOOKING: 'GET_ACTIVE_BOOKING',
  GET_UNREAD_BOOKING: 'GET_ACTIVE_BOOKING',
  GET_COMPLETED_BOOKING: 'GET_COMPLETED_BOOKING',
  GET_CANCELLED_BOOKING: 'GET_CANCELLED_BOOKING',


  RESET_ALL: 'RESET_ALL',
  SET_ROLE: 'SET_ROLE',
  SET_UID: 'SET_UID',

};
